surfit_url_list = [
    "https://www.surfit.io/explore/develop/general-dev",
    "https://www.surfit.io/explore/develop/web-dev",
    "https://www.surfit.io/explore/develop/javascript",
    "https://www.surfit.io/explore/develop/react",
    "https://www.surfit.io/explore/develop/vuejs",
    "https://www.surfit.io/explore/develop/angular",
    "https://www.surfit.io/explore/develop/nodejs",
    "https://www.surfit.io/explore/develop/java",
    "https://www.surfit.io/explore/develop/python",
    "https://www.surfit.io/explore/develop/php",
    "https://www.surfit.io/explore/develop/infra-structure",
    "https://www.surfit.io/explore/develop/database",
    "https://www.surfit.io/explore/develop/android",
    "https://www.surfit.io/explore/develop/ios",
    "https://www.surfit.io/explore/develop/git",
    "https://www.surfit.io/explore/develop/bigdata-ai-ml",
]

category_list = [
    "일반 개발",
    "웹 개발",
    "Javascript",
    "React",
    "Vue.js",
    "Angular",
    "Node.js",
    "Java",
    "Python",
    "PHP",
    "Infra Structure",
    "Database",
    "Android",
    "iOS",
    "Git",
    "빅데이터_AI_머신러닝",
]
