version: "3"

services:
  dev_db:
    image: mysql
    container_name: devook-db
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: devook_db
      MYSQL_ROOT_PASSWORD: cool
      TZ: "Asia/Seoul"

  test_db:
    image: mysql
    container_name: test-db
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: cool
      TZ: "Asia/Seoul"
